First step towards moving to KDE 4.
git-svn-id: svn+ssh://trac.godzil.net/gcc4ti@940 9552661e-59e3-4036-b4f2-dbe53926924f

diff --git a/trunk/ktigcc/configure b/trunk/ktigcc/configure
--- a/trunk/ktigcc/configure
+++ b/trunk/ktigcc/configure
@@ -1,3 +1,3 @@
 #!/bin/sh
-qmake
-if [ $? == 127 ]; then echo "error: Qt 3 required"; fi
+qmake-qt4
+if [ $? == 127 ]; then echo "error: Qt 4 required"; fi
