Install steps check for PREFIX_GCC4TI before running
This fixes the potential issue discussed in #ti that if someone
tries to run the install scripts directly, there's no check that
PREFIX_GCC4TI is defined and some commands (like rm) are unsafe.

Fix indentation

diff --git a/trunk/tigcc-linux/scripts/Install_step_1 b/trunk/tigcc-linux/scripts/Install_step_1
--- a/trunk/tigcc-linux/scripts/Install_step_1
+++ b/trunk/tigcc-linux/scripts/Install_step_1
@@ -2,6 +2,13 @@
 #
 # Apply the patch to the original sources (download directory)
 #
+
+if [ -z "$PREFIX_GCC4TI" ]; then
+    echo "Install_step_1: error: \$PREFIX_GCC4TI not defined"
+    echo "Install_step_1: error: you should not run this script directly if you don't know what you are doing."
+    exit 1
+fi
+
 echo GCC4TI script: Applying patch to original sources...
 isos=`uname -a | grep "opensolaris"`
 if [ "x$isos" = "x" ]; then
diff --git a/trunk/tigcc-linux/scripts/Install_step_4 b/trunk/tigcc-linux/scripts/Install_step_4
--- a/trunk/tigcc-linux/scripts/Install_step_4
+++ b/trunk/tigcc-linux/scripts/Install_step_4
@@ -2,6 +2,13 @@
 #
 # Install the TI-68k Developer Utilities
 #
+
+if [ -z "$PREFIX_GCC4TI" ]; then
+    echo "Install_step_4: error: \$PREFIX_GCC4TI not defined"
+    echo "Install_step_4: error: you should not run this script directly if you don't know what you are doing."
+    exit 1
+fi
+
 echo GCC4TI script: Compiling and installing the TI-68k Developer Utilities...
 isos=`uname -a | grep "opensolaris"`
 if [ "x$isos" = "x" ]; then
diff --git a/trunk/tigcc-linux/scripts/Install_step_5 b/trunk/tigcc-linux/scripts/Install_step_5
--- a/trunk/tigcc-linux/scripts/Install_step_5
+++ b/trunk/tigcc-linux/scripts/Install_step_5
@@ -3,6 +3,13 @@
 # This script installs the GCC4TI documentation
 # For this, a directory "doc" has to be created.
 #
+
+if [ -z "$PREFIX_GCC4TI" ]; then
+    echo "Install_step_5: error: \$PREFIX_GCC4TI not defined"
+    echo "Install_step_5: error: you should not run this script directly if you don't know what you are doing."
+    exit 1
+fi
+
 echo GCC4TI script: Installing GCC4TI documentation...
 
 isos=`uname -a | grep "opensolaris"`
