Install steps check for PREFIX_GCC4TI before running
This fixes the potential issue discussed in #ti that if someone
tries to run the install scripts directly, there's no check that
PREFIX_GCC4TI is defined and some commands (like rm) are unsafe.

Fix indentation

diff --git a/trunk/tigcc-linux/scripts/Install_step_2 b/trunk/tigcc-linux/scripts/Install_step_2
--- a/trunk/tigcc-linux/scripts/Install_step_2
+++ b/trunk/tigcc-linux/scripts/Install_step_2
@@ -3,6 +3,13 @@
 # This script completely configures, compiles and installs the patched tools.
 # The download tree must have been patched before doing this.
 #
+
+if [ -z "$PREFIX_GCC4TI" ]; then
+    echo "Install_step_2: error: \$PREFIX_GCC4TI not defined"
+    echo "Install_step_2: error: you should not run this script directly if you don't know what you are doing."
+    exit 1
+fi
+
 ORG_PWD=$PWD/..
 mkdir "$ORG_PWD/build"; cd "$ORG_PWD/build"; mkdir binutils; mkdir gcc;
 (cd "$ORG_PWD/scripts" && ./launch.binutils && ./launch.gcc) || exit 1
diff --git a/trunk/tigcc-linux/scripts/Install_step_3 b/trunk/tigcc-linux/scripts/Install_step_3
--- a/trunk/tigcc-linux/scripts/Install_step_3
+++ b/trunk/tigcc-linux/scripts/Install_step_3
@@ -6,6 +6,12 @@
 #
 # NOTE: the script need to be kept in sync with modifications to tigcc.tpr, fargo.tpr, flashos.tpr and pstarter.tpr !
 
+if [ -z "$PREFIX_GCC4TI" ]; then
+    echo "Install_step_3: error: \$PREFIX_GCC4TI not defined"
+    echo "Install_step_3: error: you should not run this script directly if you don't know what you are doing."
+    exit 1
+fi
+
 isbsd=`uname -a | grep "BSD"`
 isos=`uname -a | grep "opensolaris"`
 if [ "x$isbsd" = "x" -a "x$isos" = "x" ]; then
